FROM node:20.9.0

WORKDIR /usr/src/frontend

RUN apt-get update && apt-get install -y dos2unix

COPY . .

COPY entrypoint-dev.sh /usr/src/app/entrypoint.sh
RUN dos2unix /usr/src/app/entrypoint.sh && chmod 755 /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
