FROM node:20.9.0

WORKDIR /usr/src/frontend

RUN apk add --no-cache dos2unix

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

COPY entrypoint-prod.sh /usr/src/app/entrypoint.sh
RUN dos2unix /usr/src/app/entrypoint.sh && chmod 755 /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
