services:
  back:
    build: backend
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env.prod
    networks:
      - mynetwork
  front:
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    depends_on:
      - back
    env_file:
      - .env.prod
    networks:
      - mynetwork
  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    networks:
      - mynetwork
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - back
      - front
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork 
volumes:
  postgres_data:
networks:
  mynetwork: